# Generated by Django 3.2.14 on 2022-08-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Img', models.ImageField(upload_to='picture')),
                ('Desc', models.TextField()),
                ('Offer', models.BooleanField(default=False)),
            ],
        ),
    ]
