# Generated by Django 3.2.14 on 2022-08-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='Price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
